"""add_parquet_storage_to_data_sources

Revision ID: 57cfed820d74
Revises: c7d4e3f2a1b8
Create Date: 2026-06-22 12:51:03.600364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57cfed820d74'
down_revision: Union[str, None] = 'c7d4e3f2a1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parquet_path', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('schema_json', sa.Text(), nullable=True))

    with op.batch_alter_table('query_records', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_records', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_column('schema_json')
        batch_op.drop_column('parquet_path')

    # ### end Alembic commands ###
