"""initial mcp server schema

Revision ID: 835cdb8ae996
Revises: 
Create Date: 2026-06-26 02:01:01.827371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835cdb8ae996'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('query_record_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_prompts',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('arguments_json', sa.Text(), nullable=True),
    sa.Column('template_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('server_id', sa.Text(), nullable=False),
    sa.Column('created_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_prompts_server_id'), ['server_id'], unique=False)
        batch_op.create_index('uq_mcp_prompts_active_name', ['server_id', 'name'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('mcp_resources',
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('server_id', sa.Text(), nullable=False),
    sa.Column('created_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_resources_server_id'), ['server_id'], unique=False)
        batch_op.create_index('uq_mcp_resources_active_uri', ['server_id', 'uri'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('mcp_servers',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('dataset_schema_json', sa.Text(), nullable=True),
    sa.Column('physical_tables_json', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.Text(), nullable=True),
    sa.Column('connection_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uri')
    )
    op.create_table('mcp_tools',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_schema_json', sa.Text(), nullable=False),
    sa.Column('output_schema_json', sa.Text(), nullable=True),
    sa.Column('annotations_json', sa.Text(), nullable=True),
    sa.Column('sql_template', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('server_id', sa.Text(), nullable=False),
    sa.Column('created_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_tools_server_id'), ['server_id'], unique=False)
        batch_op.create_index('uq_mcp_tools_active_name', ['server_id', 'name'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('query_records',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('iteration_count', sa.Integer(), nullable=True),
    sa.Column('query_history_json', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('api_request_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_mcp_servers',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('mcp_server_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('session_id', 'mcp_server_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('session_mcp_servers')
    op.drop_table('query_records')
    with op.batch_alter_table('mcp_tools', schema=None) as batch_op:
        batch_op.drop_index('uq_mcp_tools_active_name', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_mcp_tools_server_id'))

    op.drop_table('mcp_tools')
    op.drop_table('mcp_servers')
    with op.batch_alter_table('mcp_resources', schema=None) as batch_op:
        batch_op.drop_index('uq_mcp_resources_active_uri', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_mcp_resources_server_id'))

    op.drop_table('mcp_resources')
    with op.batch_alter_table('mcp_prompts', schema=None) as batch_op:
        batch_op.drop_index('uq_mcp_prompts_active_name', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_mcp_prompts_server_id'))

    op.drop_table('mcp_prompts')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
