"""API tests for the MCP-server model: upload→create (auto-sync), duplicate rejection, external 501,
MCP JSON-RPC dispatch (tools/list+call, errors), sync version bump (soft-delete), and delete — all in
stub mode against a tmp SQLite DB."""
import csv
import io
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

import data_analysis_agent.db.session as session_module
from data_analysis_agent.db.database import Database
from data_analysis_agent.db.models import McpServerRow, McpToolRow


@pytest.fixture(autouse=True)
def _env(tmp_path, monkeypatch):
    monkeypatch.setenv("DATAANALYSIS_OPENROUTER_API_KEY", "")
    monkeypatch.setenv("DATAANALYSIS_UPLOAD_DIR", str(tmp_path / "uploads"))
    monkeypatch.setenv("DATAANALYSIS_DATASETS_DIR", str(tmp_path / "datasets"))
    monkeypatch.setenv("DATAANALYSIS_CHECKPOINT_DB", str(tmp_path / "ckpt.db"))
    db = Database(f"sqlite:///{tmp_path / 'app.db'}")
    db._init_schema()
    monkeypatch.setattr(session_module, "_db", db)
    monkeypatch.setattr(session_module, "init_db", lambda: None)
    yield
    db._dispose()
    monkeypatch.setattr(session_module, "_db", None)


@pytest.fixture
def client():
    import data_analysis_agent.llm.client as llm_module
    llm_module._client = None
    from data_analysis_agent.api import create_app
    with TestClient(create_app(), raise_server_exceptions=True) as c:
        yield c


def _csv(*rows) -> bytes:
    buf = io.StringIO()
    w = csv.writer(buf)
    for r in rows:
        w.writerow(r)
    return buf.getvalue().encode()


def _orders() -> bytes:
    return _csv(["id", "amount"], [1, 5], [2, 7])


def _create(client, name: str, data: bytes | None = None, filename: str = "orders.csv"):
    up = client.post("/mcpserver/upload", data={"dataset_name": name},
                     files={"file": (filename, data or _orders(), "text/csv")})
    assert up.status_code == 200, up.text
    uri = up.json()["uri"]
    return client.post("/mcpserver", data={"name": name, "dataset_type": "parquet", "dataset_uri": uri},
                       follow_redirects=True)


def _only_server():
    with session_module.create_db_session() as db:
        srv = db.query(McpServerRow).one()
        return srv.id, srv.version, len(srv.physical_tables)


def test_create_builds_server_and_capabilities(client):
    r = _create(client, "Sales DB")
    assert r.status_code == 200
    with session_module.create_db_session() as db:
        srv = db.query(McpServerRow).one()
        assert srv.name == "Sales DB" and srv.type == "parquet"
        assert srv.uri == "parquet:///Sales%20DB"
        assert srv.title and srv.description           # generated by the sync stub
        assert srv.version >= 2                         # create(1) + sync apply bumps to 2
        assert len(srv.physical_tables) == 1
        tools = db.query(McpToolRow).filter_by(server_id=srv.id, deleted_at=None).all()
        assert len(tools) >= 1


def test_duplicate_name_rejected(client):
    _create(client, "Dupe")
    up = client.post("/mcpserver/upload", data={"dataset_name": "Dupe"},
                     files={"file": ("b.csv", _orders(), "text/csv")})
    uri = up.json()["uri"]
    r = client.post("/mcpserver", data={"name": "Dupe", "dataset_type": "parquet", "dataset_uri": uri},
                    follow_redirects=False)
    assert r.status_code == 400


def test_create_without_upload_is_400(client):
    r = client.post("/mcpserver",
                    data={"name": "Empty", "dataset_type": "parquet", "dataset_uri": "parquet:///Empty"},
                    follow_redirects=False)
    assert r.status_code == 400


def test_external_returns_501_when_disabled(client):
    r = client.post("/mcpserver",
                    data={"dataset_type": "postgresql", "dataset_uri": "postgresql://u:p@h:5432/db"},
                    follow_redirects=False)
    assert r.status_code == 501


def test_jsonrpc_tools_list_call_and_errors(client):
    _create(client, "RPC DB")
    server_id, _, _ = _only_server()

    listed = client.post(f"/mcpserver/{server_id}",
                         json={"jsonrpc": "2.0", "id": 1, "method": "tools/list"})
    assert listed.status_code == 200
    body = listed.json()
    tools = body["result"]["tools"]
    assert tools and "inputSchema" in tools[0]
    tool_name = tools[0]["name"]

    called = client.post(f"/mcpserver/{server_id}",
                         json={"jsonrpc": "2.0", "id": 2, "method": "tools/call",
                               "params": {"name": tool_name, "arguments": {}}}).json()
    assert called["result"]["isError"] is False
    assert called["result"]["content"][0]["type"] == "text"

    # resources + prompts also list
    res = client.post(f"/mcpserver/{server_id}",
                      json={"jsonrpc": "2.0", "id": 3, "method": "resources/list"}).json()
    assert any(r["uri"].endswith("/schema") for r in res["result"]["resources"])

    # unknown method → -32601, unknown tool → -32602
    unk = client.post(f"/mcpserver/{server_id}",
                      json={"jsonrpc": "2.0", "id": 4, "method": "nope/x"}).json()
    assert unk["error"]["code"] == -32601
    bad = client.post(f"/mcpserver/{server_id}",
                      json={"jsonrpc": "2.0", "id": 5, "method": "tools/call",
                            "params": {"name": "does_not_exist", "arguments": {}}}).json()
    assert bad["error"]["code"] == -32602


def test_sync_bumps_version(client):
    _create(client, "SyncDB")
    server_id, v_before, _ = _only_server()
    r = client.post(f"/mcpserver/{server_id}/sync", follow_redirects=False)
    assert r.status_code == 303
    _, v_after, _ = _only_server()
    assert v_after == v_before + 1


def test_add_csv_adds_table(client):
    _create(client, "GrowDB")
    server_id, _, n_before = _only_server()
    r = client.post(f"/mcpserver/{server_id}/add-csv",
                    files={"file": ("customers.csv", _csv(["id", "region"], [1, "N"]), "text/csv")},
                    follow_redirects=False)
    assert r.status_code == 303
    _, _, n_after = _only_server()
    assert n_after == n_before + 1


def _rpc(client, server_id, method, params=None, rpc_id=1):
    body = {"jsonrpc": "2.0", "id": rpc_id, "method": method}
    if params is not None:
        body["params"] = params
    return client.post(f"/mcpserver/{server_id}", json=body).json()


_GOOD_TOOL = {"name": "recent_orders", "description": "Recent orders",
              "sql_template": "SELECT * FROM orders LIMIT 3",
              "input_schema": {"type": "object", "properties": {}}}


def test_tools_add_succeeds_and_cascades_prompts(client):
    _create(client, "MutDB")
    server_id, v_before, _ = _only_server()
    res = _rpc(client, server_id, "tools/add", {"definition": _GOOD_TOOL})["result"]
    assert res["ok"] is True and res["applied"]["key"] == "recent_orders"
    _, v_after, _ = _only_server()
    assert v_after == v_before + 1
    tools = _rpc(client, server_id, "tools/list")["result"]["tools"]
    assert any(t["name"] == "recent_orders" for t in tools)
    prompts = _rpc(client, server_id, "prompts/list")["result"]["prompts"]
    assert any(p["name"] == "explore_recent_orders" for p in prompts)   # additive cascade


def test_tools_add_duplicate_is_invalid_params(client):
    _create(client, "DupTool")
    server_id, _, _ = _only_server()
    _rpc(client, server_id, "tools/add", {"definition": _GOOD_TOOL})
    dup = _rpc(client, server_id, "tools/add", {"definition": _GOOD_TOOL})
    assert dup["error"]["code"] == -32602


def test_tools_add_bad_sql_is_invalid_params_and_not_persisted(client):
    _create(client, "BadSql")
    server_id, _, n0 = _only_server()
    before = len(_rpc(client, server_id, "tools/list")["result"]["tools"])
    bad = {"definition": {"name": "evil", "sql_template": "DELETE FROM orders",
                          "input_schema": {"type": "object", "properties": {}}}}
    resp = _rpc(client, server_id, "tools/add", bad)
    assert resp["error"]["code"] == -32602
    after = len(_rpc(client, server_id, "tools/list")["result"]["tools"])
    assert after == before                                              # nothing persisted


def test_prompts_add_succeeds(client):
    _create(client, "PromptDB")
    server_id, _, _ = _only_server()
    res = _rpc(client, server_id, "prompts/add",
               {"definition": {"name": "my_prompt", "description": "mine"}})["result"]
    assert res["ok"] is True
    prompts = _rpc(client, server_id, "prompts/list")["result"]["prompts"]
    assert any(p["name"] == "my_prompt" for p in prompts)


def test_unknown_mutation_method_is_method_not_found(client):
    _create(client, "NoDelete")
    server_id, _, _ = _only_server()
    resp = _rpc(client, server_id, "tools/delete", {"definition": {"name": "x"}})
    assert resp["error"]["code"] == -32601                             # not implemented → -32601


def test_delete_removes_dir_and_rows(client):
    _create(client, "ToDelete")
    server_id, _, _ = _only_server()
    with session_module.create_db_session() as db:
        srv = db.get(McpServerRow, server_id)
        dataset_dir = Path(srv.physical_tables[0]["parquet_path"]).parent
    assert dataset_dir.exists()

    r = client.post(f"/mcpserver/{server_id}/delete", follow_redirects=True)
    assert r.status_code == 200
    with session_module.create_db_session() as db:
        assert db.query(McpServerRow).count() == 0
        assert db.query(McpToolRow).count() == 0
    assert not dataset_dir.exists()
