import json
from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import Float, Index, Integer, Text, TIMESTAMP, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


def _uuid() -> str:
    """Return a new random UUID string for use as a primary-key default."""
    return str(uuid4())


def _now() -> datetime:
    """Return the current time as a timezone-aware UTC datetime."""
    return datetime.now(timezone.utc)


def _loads(raw: str | None, default):
    """Decode JSON ``raw`` or return ``default`` when unset."""
    return json.loads(raw) if raw else default


class Base(DeclarativeBase):
    pass


class McpServerRow(Base):
    """An MCP server, backed 1:1 by a dataset (one server = one dataset URI).

    Per the MCP spec a server has three kinds of children — tools, resources, prompts — generated by
    the sync pipeline and stored as rows. The dataset itself is not a separate entity: its URI, type,
    physical-table catalog (``physical_tables_json``) and generated JSONSchema (``dataset_schema_json``)
    are metadata on this row. ``name`` and ``uri`` are unique (the 1:1 dataset↔server constraint).
    """

    __tablename__ = "mcp_servers"

    id: Mapped[str] = mapped_column(Text, primary_key=True, default=_uuid)
    name: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    type: Mapped[str] = mapped_column(Text, nullable=False, default="parquet")
    uri: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1, server_default="1")
    dataset_schema_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    physical_tables_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    last_synced_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True), nullable=True)
    last_sync_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    connection_error: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now
    )

    @property
    def dataset_schema(self) -> dict:
        """Decode the generated dataset JSONSchema (empty dict if unset)."""
        return _loads(self.dataset_schema_json, {})

    @dataset_schema.setter
    def dataset_schema(self, value: dict) -> None:
        self.dataset_schema_json = json.dumps(value)

    @property
    def physical_tables(self) -> list[dict]:
        """Decode the physical-table catalog: [{table, parquet_path, columns, schema, row_count}]."""
        return _loads(self.physical_tables_json, [])

    @physical_tables.setter
    def physical_tables(self, value: list[dict]) -> None:
        self.physical_tables_json = json.dumps(value)


class _CapabilityMixin:
    """Shared versioning + soft-delete envelope for tool/resource/prompt child rows.

    Capabilities are NEVER hard-deleted by sync or the dispatcher: a removal sets ``deleted_at`` +
    ``deleted_version``. The "active" view is ``server_id = ? AND deleted_at IS NULL``.
    """

    id: Mapped[str] = mapped_column(Text, primary_key=True, default=_uuid)
    server_id: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    created_version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    deleted_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True), nullable=True)
    deleted_version: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now, onupdate=_now
    )


class McpToolRow(_CapabilityMixin, Base):
    """A canned "GET-API" MCP tool: a parameterized read-only SELECT over the server's tables."""

    __tablename__ = "mcp_tools"
    __table_args__ = (
        Index(
            "uq_mcp_tools_active_name",
            "server_id",
            "name",
            unique=True,
            sqlite_where=text("deleted_at IS NULL"),
        ),
    )

    name: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    input_schema_json: Mapped[str] = mapped_column(Text, nullable=False, default="{}")
    output_schema_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    annotations_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    sql_template: Mapped[str] = mapped_column(Text, nullable=False)

    @property
    def input_schema(self) -> dict:
        return _loads(self.input_schema_json, {})

    @input_schema.setter
    def input_schema(self, value: dict) -> None:
        self.input_schema_json = json.dumps(value)

    @property
    def output_schema(self) -> dict | None:
        return _loads(self.output_schema_json, None)

    @property
    def annotations(self) -> dict | None:
        return _loads(self.annotations_json, None)


class McpResourceRow(_CapabilityMixin, Base):
    """An MCP resource: the dataset schema, or a primary/secondary entity derived from it."""

    __tablename__ = "mcp_resources"
    __table_args__ = (
        Index(
            "uq_mcp_resources_active_uri",
            "server_id",
            "uri",
            unique=True,
            sqlite_where=text("deleted_at IS NULL"),
        ),
    )

    uri: Mapped[str] = mapped_column(Text, nullable=False)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    mime_type: Mapped[str | None] = mapped_column(Text, nullable=True)
    kind: Mapped[str] = mapped_column(Text, nullable=False, default="primary_entity")
    content_json: Mapped[str | None] = mapped_column(Text, nullable=True)

    @property
    def content(self):
        return _loads(self.content_json, None)

    @content.setter
    def content(self, value) -> None:
        self.content_json = json.dumps(value)


class McpPromptRow(_CapabilityMixin, Base):
    """An MCP prompt template over the server's tools."""

    __tablename__ = "mcp_prompts"
    __table_args__ = (
        Index(
            "uq_mcp_prompts_active_name",
            "server_id",
            "name",
            unique=True,
            sqlite_where=text("deleted_at IS NULL"),
        ),
    )

    name: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    arguments_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    template_json: Mapped[str | None] = mapped_column(Text, nullable=True)

    @property
    def arguments(self) -> list[dict]:
        return _loads(self.arguments_json, [])

    @property
    def template(self):
        return _loads(self.template_json, None)


class SessionRow(Base):
    __tablename__ = "sessions"

    id: Mapped[str] = mapped_column(Text, primary_key=True, default=_uuid)
    name: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now, onupdate=_now
    )


class SessionMcpServerRow(Base):
    """Join table linking a session to the MCP servers it spans (many-to-many)."""

    __tablename__ = "session_mcp_servers"

    session_id: Mapped[str] = mapped_column(Text, primary_key=True)
    mcp_server_id: Mapped[str] = mapped_column(Text, primary_key=True)


class QueryRecordRow(Base):
    __tablename__ = "query_records"

    id: Mapped[str] = mapped_column(Text, primary_key=True, default=_uuid)
    session_id: Mapped[str] = mapped_column(Text, nullable=False)
    question: Mapped[str] = mapped_column(Text, nullable=False)
    answer: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, default="pending")
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    iteration_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    query_history_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    input_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    output_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    total_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    estimated_cost_usd: Mapped[float | None] = mapped_column(Float, nullable=True)
    api_request_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now, onupdate=_now
    )

    @property
    def query_history(self) -> list[dict]:
        """Decode the single-level tool-call trace: [{tool, arguments, result, is_error}]."""
        return _loads(self.query_history_json, [])


class AgentRunRow(Base):
    __tablename__ = "agent_runs"

    id: Mapped[str] = mapped_column(Text, primary_key=True, default=_uuid)
    query_record_id: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, default="pending")
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now, onupdate=_now
    )
